---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app:  {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Values.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.name }}
    spec:
      serviceAccountName: chaosmonkey
      automountServiceAccountToken: true
      containers:
        - name:  {{ .Values.name }}
          image:  {{ .Values.image }}
          command:
            - bash
            - /initscript.sh
          env:
            - name: KILL_SECS
              value: "{{ .Values.killbyage.secs }}"
            - name: KILL_REGEX
              value: {{ .Values.killregex }}
            - name: WHITELIST_REGEX
              value: {{ .Values.whitelistregex }}
            - name: KILL_MEM_THRESHOLD
              value: "{{ .Values.killbymem.threshold }}"
            - name: KILL_TIME_WINDOW
              value: "{{ .Values.killbymem.timewindow }}"
            - name: KILL_TIME_STEP
              value: "{{ .Values.killbymem.step }}"
          volumeMounts:
            - name: scripts
              subPath: initscript
              mountPath: /initscript.sh
              readOnly: true
            - name: scripts
              subPath: killer
              mountPath: /killer.sh
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: {{ .Values.name }}

