---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: chaosmonkey-role
  annotations:
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaosmonkey
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: chaosmonkey
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: chaosmonkey
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosmonkey-role
subjects:
- kind: ServiceAccount
  name: chaosmonkey
  namespace: {{ .Release.Namespace }}
