#!/bin/sh
# revvyc a revvy client for reverse tunneling to ssh ports 
# Angelos Karageorgiou angelos@unix.gr Feb 2 2020 :-)
# Connect to the revvy server get your port
# attach to ssh
if ["$1" == ""]
then
  SERVER=you backlink server
else
  SERVER=$1
fi
/bin/rm -f /tmp/socket
mkfifo /tmp/socket
echo $(hostname) > /tmp/socket & # this will eventually exit
cat /tmp/socket | nc $SERVER 4443 2>&1 | socat - TCP4:127.0.0.1:22 > /tmp/socket 2>&1

