#!/bin/sh
# revvyc a revvy client for reverse tunneling to ssh ports 
# Angelos Karageorgiou angelos@unix.gr Feb 2 2020 :-)
# Connect to the revvy server get your port
# attach to ssh
TOSSH=/usr/local/bin/tos.sh
if ["$1" == ""]
then
  SERVER=192.168.1.105
else
  SERVER=$1
fi

(cat << EOF
#!/bin/sh
read line
logger "\$line"
nc 127.0.0.1 22 > /tmp/socket 2>&1
EOF
) > $TOSSH
chmod +x $TOSSH
/bin/rm -f /tmp/socket
mkfifo /tmp/socket
while [ 1 ]
do
  cat /tmp/socket |nc $SERVER 4443 2>&1 | $TOSSH
done
