#!/bin/bash
# The  inredibly smart revvy server script
# Angelos Karageorgiou angelos@unix.gr Feb 2 2020 :-)
incoming=$RANDOM
host=$(hostname)
read hostname
logger "REVVY: $hostname ssh -p $incoming pi@$host"
exec /usr/bin/socat - TCP-LISTEN:$incoming 2>&1
