# Default values for chaosmonkey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: chaosmonkey

image: debian:latest

#avoid the slash at the end of the url because prometheus sends redirects
prometheus: http://monitoring-prometheus.monitoring.svc:9090

# kill a pod after so many seconds it has been alive
# One week looks long enough
killbyage:
  enabled: true
  secs: 604800

# kill a pod with a mem utilization above a threshold
killbymem:
  enabled: true
  threshold: .2
  timewindow: 1800
  step: 300

# the pod name regex that killer will kill
# Used by all killers !
# regex: "\\-v2\\-\\|chat"
killregex: ".*"


# wake up every $RANDOM mod $wakeupsecs
wakeupsecs: 67

# wait so many secs after a kill to give the cluster time to stabilize
waitupsecs: 120

# if debug is enabled dry-run is implied
debug: true
# this is a set -x in the script
debug_pedantic: false

# skip these
whitelistregex: "kafka\\|redis\\|postgres\\|airflow"

# show some interesting stuff
log: true


